<h4>Management</h4>
Asset management is a tool for strategic planning that integrates finance, planning, engineering, personnel, and information management in the decision making process. The main objective of an asset management approach is to provide decision-makers with decision support tools based on quantitative data regarding organization resources, current condition and future performance of its facilities, and estimations of the present and future expected value of their assets. To achieve this objective, asset management embraces all the processes, tools, data and policies required to manage the assets effectively. Asset management is also known as a process of resource allocation and utilization. The framework needed to meet the needs of an agency in this process enhances policy goals and objectives, performance measurements, planning and programming, program delivery, and system monitoring and performance results. <br/><br/>
              UTEP's faculty members have conducted several research and implementation projects in the area of transportation asset management. Examples of these projects are:
              <ul>
                <li>Development of a Roadway Infrastructure Management System GIS Visual Model for the Illinois State Toll Highway Authority (ISTHA). This project included developing a software application and associated database that allow for storing, analyzing, and displaying pavement management data in ArcView GIS.</li>
                <br/>
                <li>Enhancement to Illinois Pavement Management System (PMS) for the Illinois Department of Transportation. This project included the development and implementation of a customized ArcView GIS-based PMS for Illinois (system development 1998-2001, implementation, database updates, and training in 2002 and 2003). </li>
                <br/>
                
                <li>Technical and Training Support for Metropolitan      Transportation Commission&rsquo;s Pavement Management. This project includes the      development of protocols for testing the pavement management system      sponsored by the Metropolitan Transportation Commission in California, as      well as the review of pavement performance models. The review includes:      calculation of Pavement Condition Index (PCI), PCI deterioration models,      treatment needs analysis, PCI-Driven scenario analysis and others. </li>
                <br/>
                <li>Development of an Asset Management Texas Style Approach for the Texas Department of Transportation (TxDOT). The objective of this four-year project was to develop an Asset Management approach aligned with TxDOT goals and policies to provide the necessary framework for the implementation of an Asset Management Decision Support System oriented to improve the methods and tools currently used by TxDOT to efficiently allocate resources. The scope of the project included reviewing current information management and decision support systems inside and outside of TxDOT, conducting organizational analysis interviews with key administrators and managers within TxDOT, conducting workshops, proposing performance measure strategies, and development of an implementation work plan. </li>
              </ul>
              Because of the spatial nature of transportation infrastructure systems, Geographic Information Systems (GIS), Global Positioning System (GPS), and airborne/spaceborne imagery constitute a logical information technology framework for transportation asset management. We have extensive experience in using GIS as a tool to integrate and visualize asset management data (both raw data and analysis results). UTEP has an unlimited campus-wide license of all GIS software systems, data, and training courses produced by ESRI, Inc. UTEP's capabilities in the area of geospatial technologies and sciences are not limited to GIS, but include GPS and remote sensing as well. UTEP researchers, under the NASA grant Pan American Center for Earth and Environmental Studies (PACES) (1999-2005) used GIS, GPS, and remote sensing techniques to access, process, and combine data. Examples of these projects are:</p>
              <ul>
                <li>Enhancements to El Paso's GIS-based Infrastructure Management Systems. The goal of the project was to enhance the City's infrastructure management information system to provide faster and easier methods to locate information about the storm water drainage infrastructure system and be able to locate weaknesses in the infrastructure system. The objective entailed gathering and verifying data on the City's storm water drainage infrastructure assets and integrating the data to the Geographical Information System (GIS) software. </li>
                <br/>
                <li>Development of a GIS Fiber Optics Asset Management System. The primary objective of this on-going project is to develop a GIS Fiber Optics Asset Management System (GFOAMS) for the City of El Paso.&nbsp; The major challenge in this project is to locate fiber optic conduits on the field and identify their routes. The project consists of reviewing existing records to extract data for the fiber optics network, perform a field survey to verify and collect data for the fiber optics network, integrate fiber optics data into a GIS layer, and development of a GIS fiber optics asset management system (GFOAMS).</li>
              </ul>